### ISSUE TITLE
Структура таблицы Users

### ISSUE THREAD

**Issue by Compolomus** [johncms/johncms#35]
имхо надо переделать таблицу
оставить только нужные поля с ключами, все второстипенные загнать в поле data и держать сериализацию массива в нем, на данный момент 48 полей

**Comment by rainbow-cat** [comment]
Тогда лучше уж не в одно поле с сериализацией, а в отдельную таблицу.
Что то типа user_options и связь с ней один-ко-многим от таблицы users.
